name: Build

on:
    push:
        branches: [main]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-lates

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up node
              uses: actions/setup-node@v4
              with:
                  node-version: 22

            - name: Install dependencies
              run: npm ci

            - name: Format check
              run: npm run format:check

            - name: Lint
              run: npm run lint

            - name: Type check
              run: npm run tsc:check

            - name: Build
              run: npm run build
